### 조회
GET http://127.0.0.1:8080/api/crawl

###################

### 조회
GET http://127.0.0.1:3000/api/movies

###
GET http://127.0.0.1:3000/api/movies/1

###
POST http://127.0.0.1:3000/api/movies
Content-Type: application/json

{
  "title": "콘텍트",
  "year": 2020,
  "genres": ["action", "멜로"]
}

###
DELETE  http://127.0.0.1:3000/api/movies/1

###
PATCH   http://127.0.0.1:3000/api/movies/1
Content-Type: application/json

{
  "title": "콘텍트aaa",
  "year": 2025
}


###
GET https://finance.naver.com/item/sise_time.nhn?code=005930&thistime=20210121161036
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36